### ISSUE TITLE
To upload the lib to the maven repository

### ISSUE THREAD

**Issue by RomChig** [wannesvr/dota2api#15]
@wannesvr - Hi, Van 
I'm not sure, is it possible to do that in this case, although now I'm using your lib as included jar in the project, so if you make some changes, I'll have to package jar again and replace prev with the current version, it's not as well as I’d like, are there some solutions for that, what do you think?

**Comment by wannesvr** [comment]
Hi,

Uploading to maven would be an option I think. I'd have to research it a bit since I haven't done that before.
I'll see what I can find and I'll update you on the progress.

**Comment by RomChig** [comment]
> Hi,
> 
> Uploading to maven would be an option I think. I'd have to research it a bit since I haven't done that before.
> I'll see what I can find and I'll update you on the progress.

Thanks, waiting...

**Comment by wannesvr** [comment]
Sorry for the delay. Working on this. I've requested access to the repository but have to wait for approval.

**Comment by wannesvr** [comment]
Hi @RomChig ,

I've uploaded the library to the maven repository. Could you please verify if you can fetch it with

```
<dependency>
  <groupId>io.github.wannesvr</groupId>
  <artifactId>Dota2ApiWrapper</artifactId>
  <version>1.0-SNAPSHOT</version>
</dependency>
```

If this works I will release version 1.0. Since it's the first release I'm willing to fix/improve some things before releasing it. Please let me know how you feel about this.

**Comment by RomChig** [comment]
Hi @wannesvr 
It's good news, but unfortunately, I can't load lib from maven central
`Could not find artifact io.github.wannesvr:Dota2ApiWrapper:pom:1.0 in central (https://repo.maven.apache.org/maven2) `

`Cannot resolve io.github.wannesvr:Dota2ApiWrapper:1.0-SNAPSHOT`
I've just added to the <dependency> to the <dependencies>

**Comment by wannesvr** [comment]
My bad, it isn't available as a SNAPSHOT but I was able to use it because it was in my local maven folder.
You should be able to download it now:

```
<dependency>
    <groupId>io.github.wannesvr</groupId>
    <artifactId>Dota2ApiWrapper</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by RomChig** [comment]
Yeeeap, it works 🎉🎉🎉
Btw, could you share the approach how u've done it, it's useful anyway ?)
Thanks a lot!

**Comment by wannesvr** [comment]
Nice! Good to hear.

Sure! I mainly followed their guide: [https://central.sonatype.org/publish/publish-guide/](https://central.sonatype.org/publish/publish-guide/). 

Their part is easy, you create a key to sign your jar with and you create an account on their JIRA and fill in a ticket.
I had some issues with my groupId at the start though. It has to be a domain you own since they use it to verify ownership, but I don't have any domains. This is why the groupId is `io.github.wannesvr`. They allow that as a substitute (all explained on their page).

Other than that it was a bit of a struggle to get my release working as you can see in my commits. I had some issues while using the maven-release-plugin etc. and had to make some changes to my pom.

Overall just follow their guide and Google is your friend! But if you're trying it and you're stuck I'm willing to help.

**Comment by RomChig** [comment]
Many thanks, Van 🤗
